[package]
name = "polymesh-weights"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# substrate pallets
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
pallet-timestamp = { version = "3.0.0", default-features = false }
pallet-babe = { version = "3.0.0", default-features = false }
pallet-im-online = { version = "3.0.0", default-features = false }
pallet-indices = { version = "3.0.0", default-features = false }
pallet-grandpa = { version = "3.0.0", default-features = false }
pallet-scheduler = { version = "3.0.0", default-features = false }
pallet-session = { version = "3.0.0", default-features = false }

# our pallets
pallet-asset = { path = "../asset", default-features = false }
pallet-balances = { path = "../balances", default-features = false }
pallet-staking = { path = "../staking", default-features = false }
pallet-committee = { path = "../committee", default-features = false }
pallet-compliance-manager = { path = "../compliance-manager", default-features = false  }
pallet-corporate-actions = { path = "../corporate-actions", default-features = false }
pallet-external-agents = { path = "../external-agents", default-features = false }
pallet-group = { path = "../group", default-features = false }
pallet-identity = { path = "../identity", default-features = false }
pallet-multisig = { path = "../multisig", default-features = false  }
pallet-pips = { path = "../pips", default-features = false }
pallet-portfolio = { path = "../portfolio", default-features = false  }
pallet-protocol-fee = { path = "../protocol-fee", default-features = false  }
pallet-relayer = { path = "../relayer", default-features = false }
pallet-settlement = { path = "../settlement", default-features = false  }
pallet-statistics = { path = "../statistics", default-features = false  }
pallet-sto = { path = "../sto", default-features = false  }
pallet-treasury = { path = "../treasury", default-features = false }
pallet-utility = { path = "../utility", default-features = false }
pallet-test-utils = { path = "../test-utils", default-features = false }
#polymesh-contracts = { path = "../contracts", default-features = false }
polymesh-runtime-common = { path = "../runtime/common", default-features = false }

[features]
default = ["std"]
no_std = []
std = [
    "frame-system/std",
    "pallet-asset/std",
    "pallet-babe/std",
    "pallet-staking/std",
    "pallet-balances/std",
    "pallet-compliance-manager/std",
    "pallet-corporate-actions/std",
    "pallet-grandpa/std",
    "pallet-group/std",
    "pallet-identity/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "pallet-multisig/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-protocol-fee/std",
    "pallet-relayer/std",
    "pallet-scheduler/std",
    "pallet-session/std",
    "pallet-settlement/std",
    "pallet-sto/std",
    "pallet-timestamp/std",
    "pallet-treasury/std",
    "pallet-utility/std",
    #"polymesh-contracts/std",
]
