[package]
name = "pallet-group-rpc"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false}

# RPC
pallet-group-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }

# Others
serde = { version = "1.0.104", features = ["derive"] }

# Json RPC
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"

# Substrate
codec = { package = "parity-scale-codec", version = "2.0.0" }
sp-runtime = { version = "3.0.0", default-features = false }
sp-blockchain = { version = "3.0.0", default_features = false}
sp-std = {version = "3.0.0", default_features = false }
sp-api = {version = "3.0.0", default_features = false }

[dev-dependencies]
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", tag = "v3.0.0"}
