[package]
name = "pallet-group-rpc"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
sp-api = { version = "4.0.0-dev", default_features = false }
sp-blockchain = { version = "4.0.0-dev" }
sp-core = { version = "7.0.0", default_features = false }
sp-rpc = { version = "6.0.0" }
sp-runtime = { version = "7.0.0", default_features = false }
sp-std = {version = "5.0.0", default_features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }

# Common
node-rpc = { path = "../../../rpc" }
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false}

# RPC
pallet-group-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }

# Others
serde = { version = "1.0.104", features = ["derive"] }

[dev-dependencies]
substrate-test-runtime-client = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-v5-monthly-2023-03"}
