[package]
name = "pallet-group-rpc"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false}

# RPC
pallet-group-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }

# Others
serde = { version = "1.0.104", features = ["derive"] }

# Json RPC
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-blockchain = { git = "https://github.com/PolymathNetwork/substrate", default_features = false, branch = "remove-subtype-trait"}
sp-std = {git = "https://github.com/PolymathNetwork/substrate", default_features = false, branch = "remove-subtype-trait" }
sp-api = {git = "https://github.com/PolymathNetwork/substrate", default_features = false, branch = "remove-subtype-trait" }

[dev-dependencies]
substrate-test-runtime-client = { git = "https://github.com/PolymathNetwork/substrate", default_features = false, branch = "remove-subtype-trait" }
