[package]
name = "pallet-transaction-payment"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
# Our deps
polymesh-primitives = { path = "../../primitives", default-features = false  }
polymesh-common-utilities = { path = "../common", default-features = false }

# General
serde = { version = "1.0.104", default-features = false, optional = true }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0", default-features = false }
sp-api = { version = "4.0.0-dev", default-features = false }
sp-io = { version = "6.0.0", default-features = false }
sp-runtime = { version = "6.0.0", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
pallet-timestamp = { version = "4.0.0-dev", default-features = false }

[dev-dependencies]
serde_json = "1.0.56"

[features]
default = ["std"]
no_std = []
std = [
	"serde",
	"polymesh-primitives/std",
	"polymesh-common-utilities/std",
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
]
