[package]
name = "pallet-protocol-fee-rpc"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-common-utilities = { path = "../../common", default-features = false }
pallet-protocol-fee-rpc-runtime-api = { path = "./runtime-api" }

# General
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-runtime = { git = 'https://github.com/paritytech/substrate', default_features = false, rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50" }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', default_features = false, rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50"}
sp-api = { git = 'https://github.com/paritytech/substrate', default_features = false, rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50"}
