[package]
name = "pallet-protocol-fee-rpc"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-common-utilities = { path = "../../common", default-features = false }
pallet-protocol-fee-rpc-runtime-api = { path = "./runtime-api" }

# General
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-runtime = { version = "3.0.0", default_features = false }
sp-blockchain = { version = "3.0.0", default_features = false}
sp-api = { version = "3.0.0", default_features = false}
