[package]
name = "polymesh-common-utilities"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }

# Other
serde = { version = "1.0.112", default-features = false }
serde_derive = { version = "1.0.112", optional = true, default-features = false}

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-io = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-std = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-api = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-arithmetic = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }

frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
frame-system = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }

pallet-timestamp = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
pallet-session = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }

# Only for test in STD
substrate-test-runtime-client = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2", optional = true}

# Benchmarks
frame-benchmarking = { default-features = false, git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2", optional = true }
schnorrkel = { git = "https://github.com/PolymathNetwork/schnorrkel.git", branch = "fix-simd-issue", default-features = false, optional = true }

[dev-dependencies]
lazy_static = { version = "1.4.0", default-features = false }

[features]
default = ["std", "equalize"]

# Backends
u32_backend = [ "schnorrkel/u32_backend"]
u64_backend = [ "schnorrkel/u64_backend"]
avx2_backend = [ "schnorrkel/avx2_backend"]

equalize = []
default_identity = []
no_std = ["u64_backend"]
only-staking = []
testnet = []
std = [
	"substrate-test-runtime-client",
	"serde_derive",
	"codec/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std",
	"sp-io/std",
	"sp-api/std",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"polymesh-primitives/std",
	"pallet-session/std",
	"avx2_backend"
]
runtime-benchmarks = [
	"frame-benchmarking",
	"schnorrkel",
]
