[package]
name = "polymesh-common-utilities"
version = "0.1.0"
authors = ["Polymath"]
edition = "2021"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }

# Other
serde = { version = "1.0.112", default-features = false }
serde_derive = { version = "1.0.112", optional = true, default-features = false}

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
pallet-session = { version = "4.0.0-dev", default-features = false }
pallet-timestamp = { version = "4.0.0-dev", default-features = false }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-api = { version = "4.0.0-dev", default-features = false }
sp-arithmetic = { version = "6.0.0", default-features = false }
sp-core = { version = "7.0.0", default-features = false }
sp-io = { version = "7.0.0", default-features = false }
sp-runtime = { version = "7.0.0", default-features = false }
sp-std = { version = "5.0.0", default-features = false }

# Benchmarks
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true }
schnorrkel = { version = "0.10.1", default-features = false, optional = true }

[dev-dependencies]
lazy_static = { version = "1.4.0", default-features = false }
substrate-test-runtime-client = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-v5-monthly-2023-03" }

[features]
default = ["std", "equalize"]

# Backends
u32_backend = [ "schnorrkel/u32_backend"]
u64_backend = [ "schnorrkel/u64_backend"]

equalize = []
default_identity = []
no_std = ["u64_backend"]
only-staking = []
std = [
	"u64_backend",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"polymesh-primitives/std",
	"serde/std",
	"serde_derive",
	"sp-api/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"schnorrkel",
]
