[package]
name = "pallet-external-agents"
version = "0.1.0"
authors = ["Polymath"]
edition = "2021"

[dependencies]
# Common
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }

# Our Pallets
pallet-base = { path = "../base", default-features = false }
pallet-identity = { path = "../identity", default-features = false }
pallet-permissions = { path = "../permissions", default-features = false }

# Other
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
frame-system = { version = "4.0.0-dev", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0", default-features = false }

# Only in STD
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true }

[features]
default = ["std"]
no_std = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-identity/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "serde/std",
    "serde_derive",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "polymesh-common-utilities/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
]
