[package]
name = "pallet-group-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { path = "../../../../primitives", default-features = false}
polymesh-common-utilities = { path = "../../../../common", default-features = false }

# Others
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-api = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.1" }
sp-std = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.1" }
sp-runtime = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.1" }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"serde",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"polymesh-primitives/std",
	"polymesh-common-utilities/std"
]
