[package]
name = "pallet-balances"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
pallet-permissions = { path = "../permissions", default-features = false }
pallet-transaction-payment = { path = "../transaction-payment", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }

serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false}
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }
sp-std = {  git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }

frame-system = { git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }

pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false,  branch = "at-add-dispatch-call" }

# Only for test in STD
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", branch = "at-add-dispatch-call", optional = true}

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
	"substrate-test-runtime-client",
	"serde_derive",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-api/std",
	"frame-system/std",
	"frame-support/std",
	"pallet-timestamp/std",
	"polymesh-common-utilities/std",
	"polymesh-primitives/std",
	"pallet-transaction-payment/std"
]
