[package]
name = "pallet-pips"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-common-utilities = { package = "polymesh-common-utilities", path = "../common", default-features = false  }
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }
pallet-protocol-fee = { package = "pallet-protocol-fee", path = "../protocol-fee", default-features = false }
pallet-group = { package = "pallet-group", path = "../group", default-features = false }
pallet-identity = { package = "pallet-identity", path = "../identity", default-features = false  }
pallet-balances = { package = "pallet-balances", path = "../balances", default-features = false  }
pallet-treasury = { package = "pallet-treasury", path = "../treasury", default-features = false  }

serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
shrinkwraprs = "0.3.0"


sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-serializer = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-version = { package = "sp-version", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-api = { package = "sp-api", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-timestamp = { package = "pallet-timestamp", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-committee = { package = "pallet-committee", path = "../committee", default-features = false  }

frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

[dev-dependencies]
test-client = { package = "substrate-test-runtime-client", git = "https://github.com/paritytech/substrate", rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8", default-features = false }
pallet-transaction-payment = { package = "pallet-transaction-payment", path = "../transaction-payment", default-features = false}
pallet-protocol-fee = { package = "pallet-protocol-fee", path = "../protocol-fee", default-features = false}

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
	"serde_derive",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-api/std",
	"sp-version/std",
	"pallet-timestamp/std",
	"frame-system/std",
	"frame-support/std",
	"polymesh-primitives/std",
	"polymesh-common-utilities/std",
	"pallet-balances/std",
	"pallet-group/std",
	"pallet-identity/std",
	"pallet-committee/std",
	"pallet-treasury/std",
]
