[package]
name = "pallet-pips"
version = "0.1.0"
authors = ["Polymath"]
edition = "2021"

[dependencies]
polymesh-common-utilities = { path = "../common", default-features = false  }
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }
polymesh-runtime-common = { path = "../runtime/common", default-features = false }

pallet-group = { path = "../group", default-features = false }
pallet-identity = { path = "../identity", default-features = false }
pallet-balances = { path = "../balances", default-features = false }
pallet-base = { path = "../base", default-features = false }
pallet-permissions = { path = "../permissions", default-features = false }
pallet-treasury = { path = "../treasury", default-features = false }

# General
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-core = { version = "6.0.0", default-features = false }
sp-std = { version = "4.0.0", default-features = false }
sp-io = { version = "6.0.0", default-features = false }
sp-runtime = { version = "6.0.0", default-features = false }
sp-version = { version = "5.0.0", default-features = false }
sp-api = { version = "4.0.0-dev", default-features = false }

frame-system = { package = "frame-system", version = "4.0.0-dev", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }

pallet-timestamp = { version = "4.0.0-dev", default-features = false }

# Benchmarking
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true }
rand = { version = "0.8.2", default-features = false, optional = true }
rand_chacha = { version = "0.3.0", default-features = false, optional = true }
pallet-committee = { path = "../committee", default-features = false, optional = true }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
running-ci = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "pallet-group/std",
    "pallet-identity/std",
    "pallet-timestamp/std",
    "pallet-treasury/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "polymesh-runtime-common/std",
    "serde/std",
    "serde_derive",
    "sp-api/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-version/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "rand",
    "rand_chacha",
    "pallet-committee",
]
