[package]
name = "pallet-group"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-common-utilities = { path = "../common", default-features = false}
polymesh-primitives = { path = "../../primitives", default-features = false}
pallet-identity = { path = "../identity", default-features = false }


# Others
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-std = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-io = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-version = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-api = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }

pallet-timestamp = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
frame-system = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }


[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [ 
	"serde_derive",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-api/std",
	"sp-version/std",
	"frame-system/std",
	"frame-support/std",
	"pallet-timestamp/std",
	"polymesh-primitives/std",
	"pallet-identity/std",
	"polymesh-common-utilities/std",
]
