[package]
name = "pallet-permissions"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Common
polymesh-common-utilities = { path = "../../common", default-features = false }
polymesh-primitives = { path = "../../primitives", default-features = false }

# Other
serde = { version = "1.0.104", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }

# Only for benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1", optional = true }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
    "codec/std",
    "frame-support/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "serde/std",
    "sp-runtime/std",
    "sp-std/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "polymesh-common-utilities/runtime-benchmarks",
]
