[package]
name = "pallet-staking-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
sp-api = { version = "2.0.1", default_features = false}
sp-runtime = { version = "2.0.1", default_features = false}
frame-support = { version = "2.0.1", default-features = false }

[dev-dependencies]
serde_json = "1.0.48"

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-runtime/std",
	"frame-support/std"
]
