[package]
name = "pallet-rewards"
version = "1.0.0"
authors = ["Polymath"]
edition = "2021"

[dependencies]
polymesh-common-utilities = { path = "../common", default-features = false }
polymesh-primitives = { path = "../../primitives", default-features = false }

pallet-identity = { path = "../identity", default-features = false }
pallet-staking = { path = "../staking", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-core = { version = "6.0.0", default-features = false }
sp-std = { version = "4.0.0", default-features = false }
sp-runtime = { version = "6.0.0", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true }

# Other
serde = { version = "1.0.104", default-features = false }

[features]
equalize = []
only-staking = []
default = ["std", "equalize"]
no_std = []
std = [
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-identity/std",
    "pallet-staking/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "serde/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "codec/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "polymesh-common-utilities/runtime-benchmarks",
]
