[package]
name = "pallet-pips"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }
polymesh-common-utilities = { path = "../../common", default-features = false  }

pallet-group = { path = "../group", default-features = false }
pallet-identity = { path = "../identity", default-features = false }
pallet-balances = { path = "../balances", default-features = false }
pallet-treasury = { path = "../treasury", default-features = false }

# General
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }

frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }

pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }

# Benchmarking
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.1", optional = true }
rand = { version = "0.8.2", default-features = false, optional = true }
rand_chacha = { version = "0.3.0", default-features = false, optional = true }
pallet-committee = { path = "../committee", default-features = false, optional = true }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
running-ci = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "pallet-group/std",
    "pallet-identity/std",
    "pallet-timestamp/std",
    "pallet-treasury/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "serde/std",
    "serde_derive",
    "sp-api/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-version/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "rand",
    "rand_chacha",
    "pallet-committee",
]
