[package]
name = "pallet-staking"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }
pallet-identity = { path = "../identity", default-features = false}

# General
static_assertions = "1.1.0"
serde = { version = "1.0.104", optional = true }

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-std = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-io = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2"}
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-arithmetic = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-staking = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
frame-system = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-npos-elections = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2"}

pallet-session = { features = ["historical"], git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
pallet-authorship = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
pallet-babe = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }

# Optional imports for benchmarking
frame-benchmarking = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2", optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
pallet-staking-reward-curve = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }

[features]
default = ["std"]
no_std = []
testnet = []
std = [
	"polymesh-common-utilities/std",
	"polymesh-primitives/std",
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-npos-elections/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-identity/std",
	"sp-arithmetic/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"rand_chacha",
]
