[package]
name = "custom-ink-env-types"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"

[dependencies]
ink_core = { git = "https://github.com/paritytech/ink", tag = "v2.1.0", package = "ink_core", default-features = false }
ink_prelude = { git = "https://github.com/paritytech/ink", tag = "v2.1.0", package = "ink_prelude", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate/", package = "sp-runtime", tag = "v2.0.1", default-features = false }
scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
serde = { version = "1.0.104", optional = true, features = ["derive"] }
polymesh-derive = { path = "../../../primitives_derive", default-features = false, package = "polymesh-primitives-derive"}
scale-info = { version = "0.3", default-features = false, features = ["derive"], optional = true }
derive_more = { version = "0.99", default-features = false, features = ["from", "display"] }
sp-io = { git = "https://github.com/paritytech/substrate/", package = "sp-io", tag = "v2.0.1", default-features = false, features = ["disable_panic_handler", "disable_oom", "disable_allocator"] }

[dependencies.type-metadata]
git = "https://github.com/type-metadata/type-metadata.git"
rev = "02eae9f35c40c943b56af5b60616219f2b72b47d"
default-features = false
features = ["derive"]
optional = true

[features]
default = ["std"]
std = [
    "serde",
    "scale-info",
    "scale-info/std",
    "scale/std",
    "sp-io/std",
    "sp-runtime/std",
    "ink_core/std",
]
ink-generate-abi = [
    "std",
    "type-metadata",
    "ink_core/ink-generate-abi",
]
no_std = [ ]

[workspace]
members = []
