[package]
name = "pallet-sto"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
pallet-asset = { path = "../asset", default-features = false  }
pallet-balances = { path = "../balances", default-features = false  }
pallet-base = { path = "../base", default-features = false  }
pallet-compliance-manager = { path = "../compliance-manager", default-features = false  }
pallet-external-agents = { path = "../external-agents", default-features = false }
pallet-identity = { path = "../identity", default-features = false  }
pallet-permissions = { path = "../permissions", default-features = false }
pallet-portfolio = { path = "../portfolio", default-features = false  }
pallet-settlement = { path = "../settlement", default-features = false  }
polymesh-common-utilities = { path = "../common", default-features = false }
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }

serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false  }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

sp-core = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
sp-serializer = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-version = { version = "3.0.0", default-features = false }
sp-api = { version = "3.0.0", default-features = false }
pallet-timestamp = { version = "3.0.0", default-features = false }

frame-system = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }

# Only in STD
frame-benchmarking = { default-features = false, version = "=3.0.0", optional = true }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
	"serde_derive",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-api/std",
	"frame-system/std",
	"frame-support/std",
	"frame-benchmarking/std",
	"polymesh-common-utilities/std",
	"pallet-balances/std",
	"polymesh-primitives/std",
	"pallet-identity/std",
	"pallet-asset/std",
	"pallet-settlement/std",
	"pallet-timestamp/std"
]
runtime-benchmarks = [
	"frame-benchmarking"
]
