[package]
name = "pallet-testnet"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }

pallet-identity = { path = "../identity", default-features = false }
pallet-permissions = { path = "../permissions", default-features = false }

# Others
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false  }

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }

frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1", optional = true }


[features]
default = ["std"]
testnet = []
running-ci = []
std = [
    "codec/std",
    "serde/std",
    "serde_derive",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "pallet-identity/std",
    "pallet-permissions/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "polymesh-common-utilities/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
]
