[package]
name = "pallet-permissions"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Common
polymesh-common-utilities = { path = "../common", default-features = false }
polymesh-primitives = { path = "../../primitives", default-features = false }

# Other
serde = { version = "1.0.104", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-system = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }

# Only for benchmarking
frame-benchmarking = { version = "=3.0.0", default-features = false, optional = true }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
    "codec/std",
    "frame-support/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "serde/std",
    "sp-runtime/std",
    "sp-std/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "polymesh-common-utilities/runtime-benchmarks",
]
