# wabt downgraded from 0.9.2 to 0.9.1
[package]
name = "node-testing"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/PolymeshAssociation/substrate/"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
node-primitives = { package = "polymesh-primitives", path = "../../primitives" }
node-runtime = { package = "polymesh-runtime-testnet", path = "../../pallets/runtime/testnet" }
polymesh-common-utilities =  { path = "../../pallets/common" }
pallet-transaction-payment = { path = "../../pallets/transaction-payment" }
pallet-permissions = { path = "../../pallets/permissions" }
pallet-staking = { path = "../../pallets/staking" }
pallet-balances = { path = "../../pallets/balances" }
node-executor = { path = "../executor" }

sc-service = { version = "0.10.0-dev", features = ["test-helpers"] }
sc-client-db = { version = "0.10.0-dev", features = ["kvdb-rocksdb"] }
sc-client-api = { version = "4.0.0-dev" }
codec = { package = "parity-scale-codec", version = "3.0.0" }
#pallet-contracts = { version = "4.0.0-dev" }
pallet-grandpa = { version = "4.0.0-dev" }
pallet-indices = { version = "4.0.0-dev" }
sp-keyring = { version = "7.0.0" }
sp-core = { version = "7.0.0" }
sp-io = { version = "7.0.0" }
frame-support = { version = "4.0.0-dev" }
pallet-session = { version = "4.0.0-dev" }
sp-runtime = { version = "7.0.0" }
sc-executor = { version = "0.10.0-dev" }
sp-consensus = { version = "0.10.0-dev" }
frame-system = { version = "4.0.0-dev" }
substrate-test-client = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-v5-monthly-2023-03" }
pallet-timestamp = { version = "4.0.0-dev" }
pallet-treasury = { version = "4.0.0-dev" }
wabt = "0.10.0"
sp-api = { version = "4.0.0-dev" }
sp-timestamp = { version = "4.0.0-dev", default-features = false }
sp-block-builder = { version = "4.0.0-dev" }
sc-block-builder = { version = "0.10.0-dev" }
sp-inherents = { version = "4.0.0-dev" }
sp-blockchain = { version = "4.0.0-dev" }
log = "0.4.8"
tempfile = "3.1.0"
fs_extra = "1"
futures = "0.3.1"

[dev-dependencies]
criterion = "0.3.0"
sc-cli = { version = "0.10.0-dev" }
