# wabt downgraded from 0.9.2 to 0.9.1
[package]
name = "node-testing"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/PolymathNetwork/substrate/"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
node-primitives = { package = "polymesh-primitives", path = "../../primitives" }
node-runtime = { package = "polymesh-runtime-testnet", path = "../../pallets/runtime/testnet" }
polymesh-common-utilities =  { path = "../../pallets/common" }
pallet-transaction-payment = { path = "../../pallets/transaction-payment" }
pallet-permissions = { path = "../../pallets/permissions" }
pallet-staking = { path = "../../pallets/staking" }
pallet-balances = { path = "../../pallets/balances" }
node-executor = { path = "../executor", features = ["wasmtime"] }

sc-service = { version = "0.9.0", features = ["test-helpers", "db", "wasmtime"] }
sc-client-db = { version = "0.9.0", features = ["kvdb-rocksdb", "parity-db"] }
sc-client-api = { version = "3.0.0" }
codec = { package = "parity-scale-codec", version = "2.0.0" }
pallet-contracts = { version = "3.0.0" }
pallet-grandpa = { version = "3.0.0" }
pallet-indices = { version = "3.0.0" }
sp-keyring = { version = "3.0.0" }
sp-core = { version = "3.0.0" }
sp-io = { version = "3.0.0" }
frame-support = { version = "3.0.0" }
pallet-session = { version = "3.0.0" }
sp-runtime = { version = "3.0.0" }
sc-executor = { version = "0.9.0", features = ["wasmtime"] }
sp-consensus = { version = "0.9.0" }
frame-system = { version = "3.0.0" }
substrate-test-client = { git = "https://github.com/paritytech/substrate", tag = "pallet-contracts-v3.0.0" }
pallet-timestamp = { version = "3.0.0" }
pallet-treasury = { version = "3.0.0" }
wabt = "0.10.0"
sp-api = { version = "3.0.0" }
sp-timestamp = { version = "3.0.0", default-features = false }
sp-block-builder = { version = "3.0.0" }
sc-block-builder = { version = "0.9.0" }
sp-inherents = { version = "3.0.0" }
sp-blockchain = { version = "3.0.0" }
log = "0.4.8"
tempfile = "3.1.0"
fs_extra = "1"
futures = "0.3.1"

[dev-dependencies]
criterion = "0.3.0"
sc-cli = { version = "0.9.0", features = ["wasmtime"] }
