# wabt downgraded from 0.9.2 to 0.9.1
[package]
name = "node-testing"
version = "2.0.0-rc6"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
node-primitives = { package = "polymesh-primitives", path = "../../primitives" }
node-runtime = { package = "polymesh-runtime-develop", path = "../../pallets/runtime/develop" }
polymesh-common-utilities =  { path = "../../pallets/common" }
pallet-transaction-payment = { path = "../../pallets/transaction-payment" }
pallet-staking = { path = "../../pallets/staking" }
pallet-balances = { path = "../../pallets/balances" }
sc-service = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6", features = ["test-helpers", "db"] }
sc-client-db = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6", features = ["kvdb-rocksdb", "parity-db"] }
sc-client-api = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
codec = { package = "parity-scale-codec", version = "1.3.4" }
pallet-contracts = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-indices = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-keyring = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
node-executor = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-core = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-io = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
frame-support = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-session = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-society = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sc-executor = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6", features = ["wasmtime"] }
sp-consensus = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
frame-system = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
substrate-test-client = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
wabt = "0.9.1"
sp-api = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-finality-tracker = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sc-block-builder = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-inherents = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
log = "0.4.8"
tempfile = "3.1.0"
fs_extra = "1"
futures = "0.3.1"

[dev-dependencies]
criterion = "0.3.0"
sc-cli = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
