[package]
name = "polymesh-build-tool"
version = "0.1.0"
authors = ["miguel <francisco.miguel.garcia.rodriguez@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-wasm-builder = { version = "5.0.0-dev", default-features = false}

[features]
default = ["std"]
std = []
