[package]
name = "pallet-confidential-asset"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }

# Our Pallets
pallet-balances = { path = "../balances", default-features = false  }
pallet-identity = { path = "../identity", default-features = false }
pallet-portfolio = { path = "../portfolio", default-features = false }
pallet-statistics = { path = "../statistics", default-features = false }

# Crypto
mercat = { git = "https://github.com/PolymathNetwork/cryptography.git", default-features = false, tag = "v2.2.2" }
base64 = { version = "0.12.1", default-features = false, features = ["alloc"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
frame-system = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-std = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }

# Only in STD
frame-benchmarking = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1", optional = true }

[features]
equalize = []
default = ["std", "equalize", "u64_backend"]

# Backends
u64_backend = ["mercat/u64_backend"]
avx2_backend = ["mercat/avx2_backend"]

no_std = ["mercat/no_std", "u64_backend"]
only-staking = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "mercat/std",
    "pallet-balances/std",
    "pallet-identity/std",
    "pallet-portfolio/std",
    "pallet-statistics/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "polymesh-primitives-derive/std",
    "sp-runtime/std",
    "sp-std/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
]
