[package]
name = "pallet-staking-rpc"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.2.0" }
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default_features = false, branch = "remove-subtype-trait" }
sp-blockchain = { git = "https://github.com/PolymathNetwork/substrate", default_features = false, branch = "remove-subtype-trait"}
sp-api = { git = "https://github.com/PolymathNetwork/substrate", default_features = false, branch = "remove-subtype-trait"}

pallet-staking-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }