[package]
name = "pallet-protocol-fee"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }
pallet-identity = { path = "../identity", default-features = false  }

# General
serde = { version = "1.0.104", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
frame-system = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-core = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-io = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }
sp-std = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }

[features]
default = ["std"]
no_std = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-identity/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "serde/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
]
