[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/PolymeshAssociation/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
node-primitives = { package = "polymesh-primitives", path = "../../primitives" }
node-runtime = { package = "polymesh-runtime-testnet", path = "../../pallets/runtime/testnet" }
sc-executor = { version = "0.10.0-dev" }
sp-core = { version = "7.0.0" }
sp-io = { version = "7.0.0" }
sp-state-machine = { version = "0.13.0" }
sp-trie = { version = "7.0.0" }
trie-root = "0.16.0"
frame-benchmarking = { version = "4.0.0-dev" }

[dev-dependencies]
node-testing = { path = "../testing" }
pallet-transaction-payment = { path = "../../pallets/transaction-payment" }
pallet-balances = { path = "../../pallets/balances" }

criterion = "0.3.0"
frame-support = { version = "4.0.0-dev" }
frame-system = { version = "4.0.0-dev" }
#pallet-contracts = { version = "4.0.0-dev" }
pallet-grandpa = { version = "4.0.0-dev" }
pallet-im-online = { version = "4.0.0-dev" }
pallet-indices = { version = "4.0.0-dev" }
pallet-session = { version = "4.0.0-dev" }
pallet-timestamp = { version = "4.0.0-dev" }
pallet-treasury = { version = "4.0.0-dev" }
sp-application-crypto = { version = "7.0.0" }
sp-runtime = { version = "7.0.0" }
sp-externalities = { version = "0.12.0" }
substrate-test-client = { git = "https://github.com/PolymeshAssociation/substrate", branch = "polymesh-v5-monthly-2023-03" }
wabt = "0.10.0"

[features]
stress-test = []

[[bench]]
name = "bench"
harness = false
