[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/PolymathNetwork/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
node-primitives = { package = "polymesh-primitives", path = "../../core/primitives" }
node-runtime = { package = "polymesh-runtime-testnet", path = "../../core/runtime/testnet" }
pallet-confidential = { path = "../../core/pallets/confidential" }

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.4" }
sc-executor = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2", features = ["wasmtime"] }
sp-core = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
sp-io = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
sp-state-machine = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
sp-trie = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
trie-root = "0.16.0"
frame-benchmarking = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }

[dev-dependencies]
node-testing = { path = "../testing" }
pallet-transaction-payment = { path = "../../core/pallets/transaction-payment" }
pallet-balances = { path = "../../core/pallets/balances" }
pallet-im-online = { path = "../../core/pallets/im-online" }

criterion = "0.3.0"
frame-support = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
frame-system = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
pallet-contracts = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
pallet-grandpa = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
pallet-indices = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
pallet-session = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
pallet-timestamp = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
pallet-treasury = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
sp-application-crypto = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
sp-externalities = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
substrate-test-client = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2" }
wabt = "0.10.0"

[features]
wasmtime = [
	"sc-executor/wasmtime",
]
wasmi-errno = [
	"sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
