[package]
name = "node-executor"
version = "2.0.0-rc6"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
node-primitives = { package = "polymesh-primitives", path = "../../primitives" }
node-runtime = { package = "polymesh-runtime-develop", path = "../../pallets/runtime/develop", features = ["node-bench"] }
sc-executor = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6", features = ["wasmtime"] }
sp-core = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-io = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-trie = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
trie-root = "0.16.0"
frame-benchmarking = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-confidential = { path = "../../pallets/confidential" }

[dev-dependencies]
node-testing = { path = "../testing" }
pallet-transaction-payment = { path = "../../pallets/transaction-payment" }
pallet-balances = { path = "../../pallets/balances" }

criterion = "0.3.0"
frame-support = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
frame-system = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-contracts = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-indices = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-session = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
sp-externalities = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
substrate-test-client = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc6" }
wabt = "0.9.1"

[features]
wasmi-errno = [
	"sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
