[package]
name = "node-rpc-runtime-api"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Our pallets
polymesh-primitives = { path = "../../primitives", default-features = false }
pallet-compliance-manager = { path = "../../pallets/compliance-manager", default-features = false }
pallet-pips = { path = "../../pallets/pips", default-features = false }
pallet-portfolio = { path = "../../pallets/portfolio", default-features = false }
pallet-identity = { path = "../../pallets/identity", default-features = false }
pallet-transaction-payment = { path = "../../pallets/transaction-payment", default-features = false }

# Other
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-api = { version = "2.0.1", default_features = false }
sp-std = { version = "2.0.1", default_features = false }
sp-runtime = { version = "2.0.1", default_features = false }
frame-support = { version = "2.0.1", default-features = false }
frame-system = { version = "2.0.1", default-features = false }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-compliance-manager/std",
    "pallet-identity/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-transaction-payment/std",
    "polymesh-primitives/std",
    "serde",
    "sp-api/std",
    "sp-runtime/std",
    "sp-std/std",
]
