[package]
name = "node-rpc-runtime-api"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Our pallets
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-common-utilities = { path = "../../pallets/common", default-features = false }
pallet-compliance-manager = { path = "../../pallets/compliance-manager", default-features = false }
pallet-pips = { path = "../../pallets/pips", default-features = false }
pallet-portfolio = { path = "../../pallets/portfolio", default-features = false }
pallet-identity = { path = "../../pallets/identity", default-features = false }
pallet-transaction-payment = { path = "../../pallets/transaction-payment", default-features = false }

# Other
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-api = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.1" }
sp-std = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.1" }
sp-runtime = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.1" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
testnet = ["polymesh-common-utilities/testnet"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-compliance-manager/std",
    "polymesh-common-utilities/std",
    "pallet-identity/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-transaction-payment/std",
    "polymesh-primitives/std",
    "serde",
    "sp-api/std",
    "sp-runtime/std",
    "sp-std/std",
]
