[package]
name = "pallet-confidential"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }
polymesh-common-utilities = { path = "../../common", default-features = false }

pallet-identity = { path = "../identity", default-features = false }
pallet-asset = { path = "../asset", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-io = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-std = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-api = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-arithmetic = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }

frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
frame-system = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }

pallet-timestamp = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }

sp-runtime-interface = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }

# Crypto
rand_core = { version = "0.5", default-features = false }
rand = { version = "0.7.3", default-features = false, optional = true }
cryptography_core = { git = "https://github.com/PolymathNetwork/cryptography.git", default-features = false, tag = "v2.2.2" }

# Only Benchmarking
frame-benchmarking = { default-features = false, git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1", optional = true }

[features]
equalize = []
only-staking = []
default = ["std", "equalize", "u64_backend"]

# Backends
u64_backend = ["cryptography_core/u64_backend"]
avx2_backend = ["cryptography_core/avx2_backend"]

no_std = [
    "cryptography_core/no_std",
    "u64_backend"
]

std = [
    "rand/std",
    "rand_core/std",
    "cryptography_core/std",
    "codec/std",
    "sp-core/std",
    "sp-std/std",
    "sp-io/std",
    "sp-api/std",
    "sp-arithmetic/std",
    "sp-runtime/std",
    "sp-runtime-interface/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "polymesh-primitives/std",
    "pallet-identity/std",
    "pallet-asset/std",
]

runtime-benchmarks = [
    "polymesh-common-utilities/runtime-benchmarks",
    "pallet-asset/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "frame-benchmarking",
]
